#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBH")]
public partial class QLBHDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_DonViTinh(tbl_DonViTinh instance);
  partial void Updatetbl_DonViTinh(tbl_DonViTinh instance);
  partial void Deletetbl_DonViTinh(tbl_DonViTinh instance);
  partial void Inserttbl_ThanhPham(tbl_ThanhPham instance);
  partial void Updatetbl_ThanhPham(tbl_ThanhPham instance);
  partial void Deletetbl_ThanhPham(tbl_ThanhPham instance);
  partial void Inserttbl_NhomHang(tbl_NhomHang instance);
  partial void Updatetbl_NhomHang(tbl_NhomHang instance);
  partial void Deletetbl_NhomHang(tbl_NhomHang instance);
  partial void Inserttbl_KhachHang(tbl_KhachHang instance);
  partial void Updatetbl_KhachHang(tbl_KhachHang instance);
  partial void Deletetbl_KhachHang(tbl_KhachHang instance);
  partial void Inserttbl_NCC(tbl_NCC instance);
  partial void Updatetbl_NCC(tbl_NCC instance);
  partial void Deletetbl_NCC(tbl_NCC instance);
  partial void Inserttbl_QuiDoi(tbl_QuiDoi instance);
  partial void Updatetbl_QuiDoi(tbl_QuiDoi instance);
  partial void Deletetbl_QuiDoi(tbl_QuiDoi instance);
  partial void Inserttbl_CTQuyDoi(tbl_CTQuyDoi instance);
  partial void Updatetbl_CTQuyDoi(tbl_CTQuyDoi instance);
  partial void Deletetbl_CTQuyDoi(tbl_CTQuyDoi instance);
  partial void Inserttbl_HangHoa(tbl_HangHoa instance);
  partial void Updatetbl_HangHoa(tbl_HangHoa instance);
  partial void Deletetbl_HangHoa(tbl_HangHoa instance);
  #endregion
	
	public QLBHDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLBHConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public QLBHDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLBHDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLBHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QLBHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_DonViTinh> tbl_DonViTinhs
	{
		get
		{
			return this.GetTable<tbl_DonViTinh>();
		}
	}
	
	public System.Data.Linq.Table<tbl_ThanhPham> tbl_ThanhPhams
	{
		get
		{
			return this.GetTable<tbl_ThanhPham>();
		}
	}
	
	public System.Data.Linq.Table<tbl_NhomHang> tbl_NhomHangs
	{
		get
		{
			return this.GetTable<tbl_NhomHang>();
		}
	}
	
	public System.Data.Linq.Table<tbl_KhachHang> tbl_KhachHangs
	{
		get
		{
			return this.GetTable<tbl_KhachHang>();
		}
	}
	
	public System.Data.Linq.Table<tbl_NCC> tbl_NCCs
	{
		get
		{
			return this.GetTable<tbl_NCC>();
		}
	}
	
	public System.Data.Linq.Table<tbl_QuiDoi> tbl_QuiDois
	{
		get
		{
			return this.GetTable<tbl_QuiDoi>();
		}
	}
	
	public System.Data.Linq.Table<tbl_CTQuyDoi> tbl_CTQuyDois
	{
		get
		{
			return this.GetTable<tbl_CTQuyDoi>();
		}
	}
	
	public System.Data.Linq.Table<tbl_HangHoa> tbl_HangHoas
	{
		get
		{
			return this.GetTable<tbl_HangHoa>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DonViTinh")]
public partial class tbl_DonViTinh : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _TenDonViTinh;
	
	private EntitySet<tbl_CTQuyDoi> _tbl_CTQuyDois;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenDonViTinhChanging(string value);
    partial void OnTenDonViTinhChanged();
    #endregion
	
	public tbl_DonViTinh()
	{
		this._tbl_CTQuyDois = new EntitySet<tbl_CTQuyDoi>(new Action<tbl_CTQuyDoi>(this.attach_tbl_CTQuyDois), new Action<tbl_CTQuyDoi>(this.detach_tbl_CTQuyDois));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonViTinh", DbType="NVarChar(50)")]
	public string TenDonViTinh
	{
		get
		{
			return this._TenDonViTinh;
		}
		set
		{
			if ((this._TenDonViTinh != value))
			{
				this.OnTenDonViTinhChanging(value);
				this.SendPropertyChanging();
				this._TenDonViTinh = value;
				this.SendPropertyChanged("TenDonViTinh");
				this.OnTenDonViTinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_DonViTinh_tbl_CTQuyDoi", Storage="_tbl_CTQuyDois", ThisKey="ID", OtherKey="DonViTinhID")]
	public EntitySet<tbl_CTQuyDoi> tbl_CTQuyDois
	{
		get
		{
			return this._tbl_CTQuyDois;
		}
		set
		{
			this._tbl_CTQuyDois.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbl_CTQuyDois(tbl_CTQuyDoi entity)
	{
		this.SendPropertyChanging();
		entity.tbl_DonViTinh = this;
	}
	
	private void detach_tbl_CTQuyDois(tbl_CTQuyDoi entity)
	{
		this.SendPropertyChanging();
		entity.tbl_DonViTinh = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ThanhPham")]
public partial class tbl_ThanhPham : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _TenThanhPham;
	
	private EntitySet<tbl_CTQuyDoi> _tbl_CTQuyDois;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenThanhPhamChanging(string value);
    partial void OnTenThanhPhamChanged();
    #endregion
	
	public tbl_ThanhPham()
	{
		this._tbl_CTQuyDois = new EntitySet<tbl_CTQuyDoi>(new Action<tbl_CTQuyDoi>(this.attach_tbl_CTQuyDois), new Action<tbl_CTQuyDoi>(this.detach_tbl_CTQuyDois));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThanhPham", DbType="NVarChar(150)")]
	public string TenThanhPham
	{
		get
		{
			return this._TenThanhPham;
		}
		set
		{
			if ((this._TenThanhPham != value))
			{
				this.OnTenThanhPhamChanging(value);
				this.SendPropertyChanging();
				this._TenThanhPham = value;
				this.SendPropertyChanged("TenThanhPham");
				this.OnTenThanhPhamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_ThanhPham_tbl_CTQuyDoi", Storage="_tbl_CTQuyDois", ThisKey="ID", OtherKey="ThanhPhamID")]
	public EntitySet<tbl_CTQuyDoi> tbl_CTQuyDois
	{
		get
		{
			return this._tbl_CTQuyDois;
		}
		set
		{
			this._tbl_CTQuyDois.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbl_CTQuyDois(tbl_CTQuyDoi entity)
	{
		this.SendPropertyChanging();
		entity.tbl_ThanhPham = this;
	}
	
	private void detach_tbl_CTQuyDois(tbl_CTQuyDoi entity)
	{
		this.SendPropertyChanging();
		entity.tbl_ThanhPham = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhomHang")]
public partial class tbl_NhomHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _TenNhomHang;
	
	private EntitySet<tbl_HangHoa> _tbl_HangHoas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenNhomHangChanging(string value);
    partial void OnTenNhomHangChanged();
    #endregion
	
	public tbl_NhomHang()
	{
		this._tbl_HangHoas = new EntitySet<tbl_HangHoa>(new Action<tbl_HangHoa>(this.attach_tbl_HangHoas), new Action<tbl_HangHoa>(this.detach_tbl_HangHoas));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhomHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string TenNhomHang
	{
		get
		{
			return this._TenNhomHang;
		}
		set
		{
			if ((this._TenNhomHang != value))
			{
				this.OnTenNhomHangChanging(value);
				this.SendPropertyChanging();
				this._TenNhomHang = value;
				this.SendPropertyChanged("TenNhomHang");
				this.OnTenNhomHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhomHang_tbl_HangHoa", Storage="_tbl_HangHoas", ThisKey="ID", OtherKey="NhomHangID")]
	public EntitySet<tbl_HangHoa> tbl_HangHoas
	{
		get
		{
			return this._tbl_HangHoas;
		}
		set
		{
			this._tbl_HangHoas.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbl_HangHoas(tbl_HangHoa entity)
	{
		this.SendPropertyChanging();
		entity.tbl_NhomHang = this;
	}
	
	private void detach_tbl_HangHoas(tbl_HangHoa entity)
	{
		this.SendPropertyChanging();
		entity.tbl_NhomHang = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KhachHang")]
public partial class tbl_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _TenKH;
	
	private string _NgaySinh;
	
	private System.Nullable<int> _MST;
	
	private string _Email;
	
	private string _DiaChi;
	
	private string _SDT;
	
	private byte _LoaiKH;
	
	private string _GhiChu;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnMSTChanging(System.Nullable<int> value);
    partial void OnMSTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnLoaiKHChanging(byte value);
    partial void OnLoaiKHChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
	
	public tbl_KhachHang()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string TenKH
	{
		get
		{
			return this._TenKH;
		}
		set
		{
			if ((this._TenKH != value))
			{
				this.OnTenKHChanging(value);
				this.SendPropertyChanging();
				this._TenKH = value;
				this.SendPropertyChanged("TenKH");
				this.OnTenKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="VarChar(50)")]
	public string NgaySinh
	{
		get
		{
			return this._NgaySinh;
		}
		set
		{
			if ((this._NgaySinh != value))
			{
				this.OnNgaySinhChanging(value);
				this.SendPropertyChanging();
				this._NgaySinh = value;
				this.SendPropertyChanged("NgaySinh");
				this.OnNgaySinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MST", DbType="Int")]
	public System.Nullable<int> MST
	{
		get
		{
			return this._MST;
		}
		set
		{
			if ((this._MST != value))
			{
				this.OnMSTChanging(value);
				this.SendPropertyChanging();
				this._MST = value;
				this.SendPropertyChanged("MST");
				this.OnMSTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(350)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
	public string SDT
	{
		get
		{
			return this._SDT;
		}
		set
		{
			if ((this._SDT != value))
			{
				this.OnSDTChanging(value);
				this.SendPropertyChanging();
				this._SDT = value;
				this.SendPropertyChanged("SDT");
				this.OnSDTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKH", DbType="TinyInt NOT NULL")]
	public byte LoaiKH
	{
		get
		{
			return this._LoaiKH;
		}
		set
		{
			if ((this._LoaiKH != value))
			{
				this.OnLoaiKHChanging(value);
				this.SendPropertyChanging();
				this._LoaiKH = value;
				this.SendPropertyChanged("LoaiKH");
				this.OnLoaiKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
	public string GhiChu
	{
		get
		{
			return this._GhiChu;
		}
		set
		{
			if ((this._GhiChu != value))
			{
				this.OnGhiChuChanging(value);
				this.SendPropertyChanging();
				this._GhiChu = value;
				this.SendPropertyChanged("GhiChu");
				this.OnGhiChuChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NCC")]
public partial class tbl_NCC : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _TenNCC;
	
	private string _CongTy;
	
	private string _Email;
	
	private string _SDT;
	
	private string _DiaChi;
	
	private string _MST;
	
	private string _GhiChu;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnCongTyChanging(string value);
    partial void OnCongTyChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnMSTChanging(string value);
    partial void OnMSTChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
	
	public tbl_NCC()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string TenNCC
	{
		get
		{
			return this._TenNCC;
		}
		set
		{
			if ((this._TenNCC != value))
			{
				this.OnTenNCCChanging(value);
				this.SendPropertyChanging();
				this._TenNCC = value;
				this.SendPropertyChanged("TenNCC");
				this.OnTenNCCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTy", DbType="NVarChar(250)")]
	public string CongTy
	{
		get
		{
			return this._CongTy;
		}
		set
		{
			if ((this._CongTy != value))
			{
				this.OnCongTyChanging(value);
				this.SendPropertyChanging();
				this._CongTy = value;
				this.SendPropertyChanged("CongTy");
				this.OnCongTyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20)")]
	public string SDT
	{
		get
		{
			return this._SDT;
		}
		set
		{
			if ((this._SDT != value))
			{
				this.OnSDTChanging(value);
				this.SendPropertyChanging();
				this._SDT = value;
				this.SendPropertyChanged("SDT");
				this.OnSDTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MST", DbType="NVarChar(150)")]
	public string MST
	{
		get
		{
			return this._MST;
		}
		set
		{
			if ((this._MST != value))
			{
				this.OnMSTChanging(value);
				this.SendPropertyChanging();
				this._MST = value;
				this.SendPropertyChanged("MST");
				this.OnMSTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
	public string GhiChu
	{
		get
		{
			return this._GhiChu;
		}
		set
		{
			if ((this._GhiChu != value))
			{
				this.OnGhiChuChanging(value);
				this.SendPropertyChanging();
				this._GhiChu = value;
				this.SendPropertyChanged("GhiChu");
				this.OnGhiChuChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_QuiDoi")]
public partial class tbl_QuiDoi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _HangHoaID;
	
	private System.Nullable<System.DateTime> _TuNgay;
	
	private System.Nullable<System.DateTime> _DenNgay;
	
	private EntitySet<tbl_CTQuyDoi> _tbl_CTQuyDois;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHangHoaIDChanging(System.Nullable<int> value);
    partial void OnHangHoaIDChanged();
    partial void OnTuNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnTuNgayChanged();
    partial void OnDenNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnDenNgayChanged();
    #endregion
	
	public tbl_QuiDoi()
	{
		this._tbl_CTQuyDois = new EntitySet<tbl_CTQuyDoi>(new Action<tbl_CTQuyDoi>(this.attach_tbl_CTQuyDois), new Action<tbl_CTQuyDoi>(this.detach_tbl_CTQuyDois));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangHoaID", DbType="Int")]
	public System.Nullable<int> HangHoaID
	{
		get
		{
			return this._HangHoaID;
		}
		set
		{
			if ((this._HangHoaID != value))
			{
				this.OnHangHoaIDChanging(value);
				this.SendPropertyChanging();
				this._HangHoaID = value;
				this.SendPropertyChanged("HangHoaID");
				this.OnHangHoaIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuNgay", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> TuNgay
	{
		get
		{
			return this._TuNgay;
		}
		set
		{
			if ((this._TuNgay != value))
			{
				this.OnTuNgayChanging(value);
				this.SendPropertyChanging();
				this._TuNgay = value;
				this.SendPropertyChanged("TuNgay");
				this.OnTuNgayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenNgay", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> DenNgay
	{
		get
		{
			return this._DenNgay;
		}
		set
		{
			if ((this._DenNgay != value))
			{
				this.OnDenNgayChanging(value);
				this.SendPropertyChanging();
				this._DenNgay = value;
				this.SendPropertyChanged("DenNgay");
				this.OnDenNgayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_QuiDoi_tbl_CTQuyDoi", Storage="_tbl_CTQuyDois", ThisKey="ID", OtherKey="QuiDoiID")]
	public EntitySet<tbl_CTQuyDoi> tbl_CTQuyDois
	{
		get
		{
			return this._tbl_CTQuyDois;
		}
		set
		{
			this._tbl_CTQuyDois.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbl_CTQuyDois(tbl_CTQuyDoi entity)
	{
		this.SendPropertyChanging();
		entity.tbl_QuiDoi = this;
	}
	
	private void detach_tbl_CTQuyDois(tbl_CTQuyDoi entity)
	{
		this.SendPropertyChanging();
		entity.tbl_QuiDoi = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CTQuyDoi")]
public partial class tbl_CTQuyDoi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _QuiDoiID;
	
	private System.Nullable<int> _ThanhPhamID;
	
	private System.Nullable<int> _DonViTinhID;
	
	private System.Nullable<double> _SoLuong;
	
	private EntityRef<tbl_QuiDoi> _tbl_QuiDoi;
	
	private EntityRef<tbl_DonViTinh> _tbl_DonViTinh;
	
	private EntityRef<tbl_ThanhPham> _tbl_ThanhPham;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnQuiDoiIDChanging(System.Nullable<int> value);
    partial void OnQuiDoiIDChanged();
    partial void OnThanhPhamIDChanging(System.Nullable<int> value);
    partial void OnThanhPhamIDChanged();
    partial void OnDonViTinhIDChanging(System.Nullable<int> value);
    partial void OnDonViTinhIDChanged();
    partial void OnSoLuongChanging(System.Nullable<double> value);
    partial void OnSoLuongChanged();
    #endregion
	
	public tbl_CTQuyDoi()
	{
		this._tbl_QuiDoi = default(EntityRef<tbl_QuiDoi>);
		this._tbl_DonViTinh = default(EntityRef<tbl_DonViTinh>);
		this._tbl_ThanhPham = default(EntityRef<tbl_ThanhPham>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuiDoiID", DbType="Int")]
	public System.Nullable<int> QuiDoiID
	{
		get
		{
			return this._QuiDoiID;
		}
		set
		{
			if ((this._QuiDoiID != value))
			{
				if (this._tbl_QuiDoi.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnQuiDoiIDChanging(value);
				this.SendPropertyChanging();
				this._QuiDoiID = value;
				this.SendPropertyChanged("QuiDoiID");
				this.OnQuiDoiIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhPhamID", DbType="Int")]
	public System.Nullable<int> ThanhPhamID
	{
		get
		{
			return this._ThanhPhamID;
		}
		set
		{
			if ((this._ThanhPhamID != value))
			{
				if (this._tbl_ThanhPham.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnThanhPhamIDChanging(value);
				this.SendPropertyChanging();
				this._ThanhPhamID = value;
				this.SendPropertyChanged("ThanhPhamID");
				this.OnThanhPhamIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinhID", DbType="Int")]
	public System.Nullable<int> DonViTinhID
	{
		get
		{
			return this._DonViTinhID;
		}
		set
		{
			if ((this._DonViTinhID != value))
			{
				if (this._tbl_DonViTinh.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnDonViTinhIDChanging(value);
				this.SendPropertyChanging();
				this._DonViTinhID = value;
				this.SendPropertyChanged("DonViTinhID");
				this.OnDonViTinhIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Float")]
	public System.Nullable<double> SoLuong
	{
		get
		{
			return this._SoLuong;
		}
		set
		{
			if ((this._SoLuong != value))
			{
				this.OnSoLuongChanging(value);
				this.SendPropertyChanging();
				this._SoLuong = value;
				this.SendPropertyChanged("SoLuong");
				this.OnSoLuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_QuiDoi_tbl_CTQuyDoi", Storage="_tbl_QuiDoi", ThisKey="QuiDoiID", OtherKey="ID", IsForeignKey=true)]
	public tbl_QuiDoi tbl_QuiDoi
	{
		get
		{
			return this._tbl_QuiDoi.Entity;
		}
		set
		{
			tbl_QuiDoi previousValue = this._tbl_QuiDoi.Entity;
			if (((previousValue != value) 
						|| (this._tbl_QuiDoi.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_QuiDoi.Entity = null;
					previousValue.tbl_CTQuyDois.Remove(this);
				}
				this._tbl_QuiDoi.Entity = value;
				if ((value != null))
				{
					value.tbl_CTQuyDois.Add(this);
					this._QuiDoiID = value.ID;
				}
				else
				{
					this._QuiDoiID = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbl_QuiDoi");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_DonViTinh_tbl_CTQuyDoi", Storage="_tbl_DonViTinh", ThisKey="DonViTinhID", OtherKey="ID", IsForeignKey=true)]
	public tbl_DonViTinh tbl_DonViTinh
	{
		get
		{
			return this._tbl_DonViTinh.Entity;
		}
		set
		{
			tbl_DonViTinh previousValue = this._tbl_DonViTinh.Entity;
			if (((previousValue != value) 
						|| (this._tbl_DonViTinh.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_DonViTinh.Entity = null;
					previousValue.tbl_CTQuyDois.Remove(this);
				}
				this._tbl_DonViTinh.Entity = value;
				if ((value != null))
				{
					value.tbl_CTQuyDois.Add(this);
					this._DonViTinhID = value.ID;
				}
				else
				{
					this._DonViTinhID = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbl_DonViTinh");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_ThanhPham_tbl_CTQuyDoi", Storage="_tbl_ThanhPham", ThisKey="ThanhPhamID", OtherKey="ID", IsForeignKey=true)]
	public tbl_ThanhPham tbl_ThanhPham
	{
		get
		{
			return this._tbl_ThanhPham.Entity;
		}
		set
		{
			tbl_ThanhPham previousValue = this._tbl_ThanhPham.Entity;
			if (((previousValue != value) 
						|| (this._tbl_ThanhPham.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_ThanhPham.Entity = null;
					previousValue.tbl_CTQuyDois.Remove(this);
				}
				this._tbl_ThanhPham.Entity = value;
				if ((value != null))
				{
					value.tbl_CTQuyDois.Add(this);
					this._ThanhPhamID = value.ID;
				}
				else
				{
					this._ThanhPhamID = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbl_ThanhPham");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HangHoa")]
public partial class tbl_HangHoa : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _TenHH;
	
	private System.Nullable<int> _NhomHangID;
	
	private System.Nullable<decimal> _GiaBan;
	
	private System.Nullable<int> _SoLuong;
	
	private string _HinhAnh;
	
	private string _MoTa;
	
	private string _DVT;
	
	private EntityRef<tbl_NhomHang> _tbl_NhomHang;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenHHChanging(string value);
    partial void OnTenHHChanged();
    partial void OnNhomHangIDChanging(System.Nullable<int> value);
    partial void OnNhomHangIDChanged();
    partial void OnGiaBanChanging(System.Nullable<decimal> value);
    partial void OnGiaBanChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    #endregion
	
	public tbl_HangHoa()
	{
		this._tbl_NhomHang = default(EntityRef<tbl_NhomHang>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHH", DbType="NVarChar(150)")]
	public string TenHH
	{
		get
		{
			return this._TenHH;
		}
		set
		{
			if ((this._TenHH != value))
			{
				this.OnTenHHChanging(value);
				this.SendPropertyChanging();
				this._TenHH = value;
				this.SendPropertyChanged("TenHH");
				this.OnTenHHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomHangID", DbType="Int")]
	public System.Nullable<int> NhomHangID
	{
		get
		{
			return this._NhomHangID;
		}
		set
		{
			if ((this._NhomHangID != value))
			{
				if (this._tbl_NhomHang.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnNhomHangIDChanging(value);
				this.SendPropertyChanging();
				this._NhomHangID = value;
				this.SendPropertyChanged("NhomHangID");
				this.OnNhomHangIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> GiaBan
	{
		get
		{
			return this._GiaBan;
		}
		set
		{
			if ((this._GiaBan != value))
			{
				this.OnGiaBanChanging(value);
				this.SendPropertyChanging();
				this._GiaBan = value;
				this.SendPropertyChanged("GiaBan");
				this.OnGiaBanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
	public System.Nullable<int> SoLuong
	{
		get
		{
			return this._SoLuong;
		}
		set
		{
			if ((this._SoLuong != value))
			{
				this.OnSoLuongChanging(value);
				this.SendPropertyChanging();
				this._SoLuong = value;
				this.SendPropertyChanged("SoLuong");
				this.OnSoLuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
	public string HinhAnh
	{
		get
		{
			return this._HinhAnh;
		}
		set
		{
			if ((this._HinhAnh != value))
			{
				this.OnHinhAnhChanging(value);
				this.SendPropertyChanging();
				this._HinhAnh = value;
				this.SendPropertyChanged("HinhAnh");
				this.OnHinhAnhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
	public string MoTa
	{
		get
		{
			return this._MoTa;
		}
		set
		{
			if ((this._MoTa != value))
			{
				this.OnMoTaChanging(value);
				this.SendPropertyChanging();
				this._MoTa = value;
				this.SendPropertyChanged("MoTa");
				this.OnMoTaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(20)")]
	public string DVT
	{
		get
		{
			return this._DVT;
		}
		set
		{
			if ((this._DVT != value))
			{
				this.OnDVTChanging(value);
				this.SendPropertyChanging();
				this._DVT = value;
				this.SendPropertyChanged("DVT");
				this.OnDVTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhomHang_tbl_HangHoa", Storage="_tbl_NhomHang", ThisKey="NhomHangID", OtherKey="ID", IsForeignKey=true, DeleteRule="CASCADE")]
	public tbl_NhomHang tbl_NhomHang
	{
		get
		{
			return this._tbl_NhomHang.Entity;
		}
		set
		{
			tbl_NhomHang previousValue = this._tbl_NhomHang.Entity;
			if (((previousValue != value) 
						|| (this._tbl_NhomHang.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_NhomHang.Entity = null;
					previousValue.tbl_HangHoas.Remove(this);
				}
				this._tbl_NhomHang.Entity = value;
				if ((value != null))
				{
					value.tbl_HangHoas.Add(this);
					this._NhomHangID = value.ID;
				}
				else
				{
					this._NhomHangID = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbl_NhomHang");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
